package data

import (
	"context"
	"crypto/rand"
	"crypto/sha256"
	"database/sql"
	"time"

	"greenlight.cnoua.org/internal/validator"
)

// Define constants for the token scope. For now just "activation" scope.
const (
	ScopeActivation = "activation"
)

// Define a Token struct to hold the data for an individual token. This includes
// the plaintext and hashed versions of the token, associated user ID, expiry
// time and scope.
type Token struct {
	Plaintext string
	Hash      []byte
	UserID    int
	Expiry    time.Time
	Scope     string
}

func generateToken(userID int, ttl time.Duration, scope string) *Token {
	// Create a Token instance. In it, we set the Plaintext field to be a random
	// token generated by rand.Text(), and also set the values for the user ID,
	// expiry, and scope of the token. We add the provided ttl (time-to-live)
	// duration argument to the current time to get the expiry date.
	token := &Token{
		Plaintext: rand.Text(),
		UserID:    userID,
		Expiry:    time.Now().Add(ttl),
		Scope:     scope,
	}

	// Generate a SHA-256 hash of the plaintext token string. This will be the value
	// that we store in the 'hash' column of our database table. Note that the
	// sha256.Sum256() function returns an *array* of length 32, so to make it easier
	// to work with, we convert it to a slice using the [:] operator before storing it.
	hash := sha256.Sum256([]byte(token.Plaintext))
	token.Hash = hash[:]

	return token
}

// Check that the plaintext token has been provided and is exactly 26 bytes long.
func ValidateTokenPlainText(v *validator.Validator, tokenPlainText string) {
	v.Check(tokenPlainText != "", "token", "must be provided")
	v.Check(len(tokenPlainText) == 26, "token", "must be 26 bytes long")
}

// Define the TokenModel type.
type TokenModel struct {
	DB *sql.DB
}

// New() is a shortcut to create a new Token struct and insert the data.
func (m TokenModel) New(userID int, ttl time.Duration, scope string) (*Token, error) {
	token := generateToken(userID, ttl, scope)

	err := m.Insert(token)
	return token, err
}

// Insert() adds the data for a specific token to the tokens table.
func (m TokenModel) Insert(token *Token) error {
	query := `
		INSERT INTO tokens (hash, user_id, expiry, scope)
		VALUES ($1, $2, $3, $4)`

	args := []any{token.Hash, token.UserID, token.Expiry, token.Scope}

	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
	defer cancel()

	_, err := m.DB.ExecContext(ctx, query, args...)
	return err
}

// DeleteAllForUser() deletes all tokens for a specific user & scope.
func (m TokenModel) DeleteAllForUser(scope string, userID int) error {
	query := `
		DELETE FROM tokens
		WHERE scope = $1 AND user_id = $2`

	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
	defer cancel()

	_, err := m.DB.ExecContext(ctx, query, scope, userID)
	return err
}
